// Generated by gencpp from file path_planning/IntList.msg
// DO NOT EDIT!


#ifndef PATH_PLANNING_MESSAGE_INTLIST_H
#define PATH_PLANNING_MESSAGE_INTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_planning
{
template <class ContainerAllocator>
struct IntList_
{
  typedef IntList_<ContainerAllocator> Type;

  IntList_()
    : data()  {
    }
  IntList_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::path_planning::IntList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_planning::IntList_<ContainerAllocator> const> ConstPtr;

}; // struct IntList_

typedef ::path_planning::IntList_<std::allocator<void> > IntList;

typedef boost::shared_ptr< ::path_planning::IntList > IntListPtr;
typedef boost::shared_ptr< ::path_planning::IntList const> IntListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_planning::IntList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_planning::IntList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_planning::IntList_<ContainerAllocator1> & lhs, const ::path_planning::IntList_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_planning::IntList_<ContainerAllocator1> & lhs, const ::path_planning::IntList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_planning::IntList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_planning::IntList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planning::IntList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_planning::IntList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning::IntList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_planning::IntList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_planning::IntList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "563b27884d008b0d2adff54dc1f9e4f5";
  }

  static const char* value(const ::path_planning::IntList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x563b27884d008b0dULL;
  static const uint64_t static_value2 = 0x2adff54dc1f9e4f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_planning::IntList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_planning/IntList";
  }

  static const char* value(const ::path_planning::IntList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_planning::IntList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] data\n"
;
  }

  static const char* value(const ::path_planning::IntList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_planning::IntList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_planning::IntList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_planning::IntList_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_PLANNING_MESSAGE_INTLIST_H
